In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Read all Eugene CAD data from 2015 to 2025

In [51]:
eugene_15 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2015noloc.csv")
eugene_16 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2016noloc.csv")
eugene_17 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2017noloc.csv")
eugene_18 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2018noloc.csv")
eugene_19 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2019noloc.csv")
eugene_20 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2020noloc.csv")
eugene_21 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2021noloc.csv", dtype={5: str})
eugene_22 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2022noloc.csv")
eugene_23 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2023noloc.csv")
eugene_24 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2024noloc.csv")
eugene_25 = pd.read_csv("Eugene_CAD_data_noloc/EugeneCAD2025noloc.csv", dtype={6: str})

### Concatenate All Eugene Dataset

In [52]:
all_eugene = pd.concat([eugene_15, eugene_16, eugene_17, eugene_18,eugene_19, eugene_20, eugene_21, eugene_22,
                       eugene_23, eugene_24, eugene_25], ignore_index=True)
all_eugene.shape

(1446014, 20)

### Filter data frame to calls closed as arrests

In [53]:
filter1 = all_eugene["closed_as"].isin(["ARREST"])
eugene_arrests = all_eugene[filter1]
eugene_arrests.shape

(40575, 20)

### Remove unnecessary columns

In [54]:
eugene_arrests = eugene_arrests.drop(columns=["service", "calltime", "case_id", "callsource", "secs_to_disp",
                                              "secs_to_arrv", "secs_to_close", "disp", "arrv", "priority", "primeunit",
                                             "units_dispd", "units_arrived", "month", "closecode"])

In [55]:
eugene_arrests.head()

      yr agency   inci_id              nature closed_as
20  2015   EPD   15000043             ASSAULT    ARREST
59  2015   EPD   15000116               FIGHT    ARREST
60  2015   EPD   15000117               FIGHT    ARREST
78  2015   EPD   15000175   CRIMINAL TRESPASS    ARREST
83  2015   EPD   15000185  DISORDERLY SUBJECT    ARREST

### Organize the column order

In [56]:
eugene_arrests = eugene_arrests[["inci_id", "yr", "agency", "nature", "closed_as"]]
eugene_arrests

          inci_id    yr agency              nature closed_as
20       15000043  2015   EPD              ASSAULT    ARREST
59       15000116  2015   EPD                FIGHT    ARREST
60       15000117  2015   EPD                FIGHT    ARREST
78       15000175  2015   EPD    CRIMINAL TRESPASS    ARREST
83       15000185  2015   EPD   DISORDERLY SUBJECT    ARREST
...           ...   ...    ...                 ...       ...
1445949  25327212  2025   EPD            FOLLOW UP    ARREST
1445965  25327250  2025   EPD              PROWLER    ARREST
1445969  25327266  2025   EPD          PERSON STOP    ARREST
1445991  25327323  2025   EPD              DISPUTE    ARREST
1446001  25327344  2025   EPD         TRAFFIC STOP    ARREST

[40575 rows x 5 columns]

### rename the column names

In [58]:
eugene_arrests = eugene_arrests.rename(columns={"inci_id": "Incident Number", "yr": "Year", "agency": "Responding Agency", "nature": "Initial Call Type",
                                                "closed_as": "Final Call Type"})
eugene_arrests.head()

,Incident Number,Year,Responding Agency,Initial Call Type,Final Call Type
20,15000043,2015,EPD,ASSAULT,ARREST
59,15000116,2015,EPD,FIGHT,ARREST
60,15000117,2015,EPD,FIGHT,ARREST
78,15000175,2015,EPD,CRIMINAL TRESPASS,ARREST
83,15000185,2015,EPD,DISORDERLY SUBJECT,ARREST

### Read all Springfield CAD data from 2015 to 2025

In [16]:
springfield_15 = pd.read_csv("Springfield_CAD_data/2015_spd_calls.csv")
springfield_16 = pd.read_csv("Springfield_CAD_data/2016_spd_calls.csv")
springfield_17 = pd.read_csv("Springfield_CAD_data/2017_spd_calls.csv")
springfield_18 = pd.read_csv("Springfield_CAD_data/2018_spd_calls.csv")
springfield_19 = pd.read_csv("Springfield_CAD_data/2019_spd_calls.csv")
springfield_20 = pd.read_csv("Springfield_CAD_data/2020_spd_calls.csv")
springfield_21 = pd.read_csv("Springfield_CAD_data/2021_spd_calls.csv")
springfield_22 = pd.read_csv("Springfield_CAD_data/2022_spd_calls.csv")
springfield_23 = pd.read_csv("Springfield_CAD_data/2023_spd_calls.csv")
springfield_24 = pd.read_csv("Springfield_CAD_data/2024_spd_calls.csv")
springfield_25 = pd.read_csv("Springfield_CAD_data/2025_spd_calls.csv")

### The Springfield data is missing the "Year" variable, so I'll manually add it to each data frame

In [17]:
springfield_15["yr"] = 2015
springfield_16["yr"] = 2016
springfield_17["yr"] = 2017
springfield_18["yr"] = 2018
springfield_19["yr"] = 2019
springfield_20["yr"] = 2020
springfield_21["yr"] = 2021
springfield_22["yr"] = 2022
springfield_23["yr"] = 2023
springfield_24["yr"] = 2024
springfield_25["yr"] = 2025

### The Springfield data frames are also missing information about how the call was closed

### The '2015-2025 SPD Calls with Close Codes' data sets contains values as 'Incident Number' which will be used to merge the Springfield CAD data to add a new column. The new column contains information on how the call was closed

In [35]:
closed_15 = pd.read_csv("springfield_close_codes/2015_spd_close_codes.csv")
closed_16 = pd.read_csv("springfield_close_codes/2016_spd_close_codes.csv")
closed_17 = pd.read_csv("springfield_close_codes/2017_spd_close_codes.csv")
closed_18 = pd.read_csv("springfield_close_codes/2018_spd_close_codes.csv")
closed_19 = pd.read_csv("springfield_close_codes/2019_spd_close_codes.csv")
closed_20 = pd.read_csv("springfield_close_codes/2020_spd_close_codes.csv")
closed_21 = pd.read_csv("springfield_close_codes/2021_spd_close_codes.csv")
closed_22 = pd.read_csv("springfield_close_codes/2022_spd_close_codes.csv")
closed_23 = pd.read_csv("springfield_close_codes/2023_spd_close_codes.csv")
closed_24 = pd.read_csv("springfield_close_codes/2024_spd_close_codes.csv")
closed_25 = pd.read_csv("springfield_close_codes/2025_spd_close_codes.csv")

### Merge both data frames using "Incident Number" as the column they both shared

### Keep the rows where the shared column values are in BOTH data frames in "Incident Number" column

In [36]:
merged_15 = pd.merge(springfield_15, closed_15, on='Incident Number', how='inner')
merged_16 = pd.merge(springfield_16, closed_16, on='Incident Number', how='inner')
merged_17 = pd.merge(springfield_17, closed_17, on='Incident Number', how='inner')
merged_18 = pd.merge(springfield_18, closed_18, on='Incident Number', how='inner')
merged_19 = pd.merge(springfield_19, closed_19, on='Incident Number', how='inner')
merged_20 = pd.merge(springfield_20, closed_20, on='Incident Number', how='inner')
merged_21 = pd.merge(springfield_21, closed_21, on='Incident Number', how='inner')
merged_22 = pd.merge(springfield_22, closed_22, on='Incident Number', how='inner')
merged_23 = pd.merge(springfield_23, closed_23, on='Incident Number', how='inner')
merged_24 = pd.merge(springfield_24, closed_24, on='Incident Number', how='inner')
merged_25 = pd.merge(springfield_25, closed_25, on='Incident Number', how='inner')

### Concatenate all Springfield data frames

In [43]:
all_springfield = pd.concat([merged_15, merged_16, merged_17, merged_18, merged_19, merged_20, merged_21, merged_22,
                       merged_23, merged_24, merged_25], ignore_index=True)
all_springfield["Close Code"].unique()

array(['BLDS', 'UTC ', 'DUP ', 'INFO', 'TOW ', 'PCHK', 'RTO ', 'DDIS',
       'QOA ', 'WCB ', 'ARR ', 'TRAF', 'RSLV', 'REPT', 'NOIN', 'CIT ',
       'WARN', 'REL ', 'ACC ', 'EERR', 'ADVI', 'SBCK', 'NCH ', 'WELC',
       'TAG ', 'CLC ', 'GOA ', 'FI  ', 'ASST', 'DIS ', 'UTL ', 'REPO',
       'FUP ', 'PERS', 'UNFD', 'LCSO', 'MEDX', 'PDIS', 'OSP ', 'NOAT',
       'XRPT', 'PW  ', 'UTD ', 'TIC ', '    ', 'CIV ', 'AO  ', 'TRAN',
       'TEST', 'PTOW', 'CAMP', 'UOPD', 'MVAN', 'CBCK', 'MIS ', 'NOPA',
       'FALS', 'PCO ', 'ABAN', 'QOLN', 'FIX ', 'CGP ', 'LINN', 'ACTT',
       'SPD ', 'AWO ', 'FLP ', 'PA  ', 'CANC', 'DOA ', 'DA  ', 'BENT',
       'XUTA', 'AID ', ' REL', 'SPX ', 'CCCP', ' WCB', 'GUN ', 'ROW ',
       'IMP ', 'REFS', ' DIS', 'UH  ', 'TEU ', 'CAR ', 'REFU', 'NODA'],
      dtype=object)

In [38]:
all_springfield.shape

(567654, 13)

### Filter data frame to calls closed as ARREST

In [46]:
filter2 = all_springfield["Close Code"].isin(["ARR "])
springfield_arrests = all_springfield[filter2]
springfield_arrests.head()

,Incident Number,Initial Call Type,Final Call Type,Responding Agency,Primary Responding Unit,Call Creation Time,First Dispatched Time,First Arrival Time,Clear Time,Priority,Call Creation Mechanism,yr,Close Code
162,15000022,PERSTP,IN POSSESSION OF NARCOTICS,SPD,3S12,11:42.0,11:42.0,11:42.0,09:10.0,4,SELF,2015,ARR
165,15000037,TRFSTP,DUII,SPD,3D1,25:33.0,25:33.0,25:33.0,15:27.0,4,SELF,2015,ARR
166,15000040,DSPUT,HARASSMENT,SPD,1S12,27:26.0,28:14.0,32:33.0,20:05.0,3,PHONE,2015,ARR
170,15000082,TRFSTP,DUII,SPD,3S13,21:44.0,21:45.0,21:45.0,00:07.0,4,SELF,2015,ARR
172,15000096,TRFSTP,DUII,SPD,3D2,32:45.0,32:45.0,32:45.0,21:06.0,4,SELF,2015,ARR

### Remove unnecessary columns

In [47]:
springfield_arrests = springfield_arrests.drop(columns=["Final Call Type", "Primary Responding Unit", "Call Creation Time",
                                                        "First Dispatched Time", "First Arrival Time",
                                              "Clear Time", "Priority", "Call Creation Mechanism"])

In [48]:
springfield_arrests.head()

     Incident Number Initial Call Type Responding Agency    yr Close Code
162         15000022            PERSTP              SPD   2015       ARR
165         15000037            TRFSTP              SPD   2015       ARR
166         15000040            DSPUT               SPD   2015       ARR
170         15000082            TRFSTP              SPD   2015       ARR
172         15000096            TRFSTP              SPD   2015       ARR

In [49]:
springfield_arrests.shape

(30199, 5)

### Organize 'springfield_arrests' columns to  match 'eugene_arrests' data frame

In [60]:
springfield_arrests = springfield_arrests[["Incident Number", "yr", "Responding Agency", "Initial Call Type", "Close Code"]]
springfield_arrests.head()

     Incident Number    yr Responding Agency Initial Call Type Close Code
162         15000022  2015              SPD             PERSTP       ARR
165         15000037  2015              SPD             TRFSTP       ARR
166         15000040  2015              SPD             DSPUT        ARR
170         15000082  2015              SPD             TRFSTP       ARR
172         15000096  2015              SPD             TRFSTP       ARR

### Rename 'springfield_arrests' columns to match 'eugene_arrests' data frame

In [61]:
springfield_arrests = springfield_arrests.rename(columns={"yr": "Year", "Close Code": "Final Call Type"})
springfield_arrests.head()

     Incident Number  Year Responding Agency Initial Call Type Final Call Type
162         15000022  2015              SPD             PERSTP            ARR
165         15000037  2015              SPD             TRFSTP            ARR
166         15000040  2015              SPD             DSPUT             ARR
170         15000082  2015              SPD             TRFSTP            ARR
172         15000096  2015              SPD             TRFSTP            ARR

### Replace 'ARR' value with 'ARREST'

In [67]:
springfield_arrests = springfield_arrests.replace("ARR ", "ARREST")

In [68]:
springfield_arrests.head()

     Incident Number  Year Responding Agency Initial Call Type Final Call Type
162         15000022  2015              SPD             PERSTP          ARREST
165         15000037  2015              SPD             TRFSTP          ARREST
166         15000040  2015              SPD             DSPUT           ARREST
170         15000082  2015              SPD             TRFSTP          ARREST
172         15000096  2015              SPD             TRFSTP          ARREST

### Concatenate the clean Springfield CAD data frame with the clean Eugene CAD data frame

In [69]:
eugene_springfield = pd.concat([eugene_arrests, springfield_arrests], ignore_index=True)
eugene_springfield.head()

   Incident Number  Year Responding Agency   Initial Call Type Final Call Type
0         15000043  2015              EPD              ASSAULT          ARREST
1         15000116  2015              EPD                FIGHT          ARREST
2         15000117  2015              EPD                FIGHT          ARREST
3         15000175  2015              EPD    CRIMINAL TRESPASS          ARREST
4         15000185  2015              EPD   DISORDERLY SUBJECT          ARREST

### Check for any null values

In [70]:
eugene_springfield.shape

(70774, 5)

In [71]:
eugene_springfield.isnull().sum().sum()

np.int64(0)

### Check for any duplicate incident Number values

In [72]:
np.size(eugene_springfield["Incident Number"].unique())

70774

In [73]:
eugene_springfield.shape

(70774, 5)

### Convert final data frame into a csv file

In [74]:
eugene_springfield.to_csv("Eugene_Springfield_Calls.csv", index=False)